name: dev.deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Setup Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: '10.14.1'

      - name: Install Python Dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -Ur requirements.txt; fi
          if [ -f requirements.txt ]; then pip install --target="./application" -Ur requirements.txt; fi
          if [ -f test_requirements.txt ]; then pip install -Ur test_requirements.txt; fi
          if [ -f infra_requirements.txt ]; then pip install -Ur infra_requirements.txt; fi

      - name: Install AWS CDK
        run: sudo npm install -g aws-cdk

      - name: Bootstrapping AWS
        run: cdk bootstrap aws://${{ secrets.PROD_ACCOUNT_NUMBER}}/$AWS_REGION
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'

      - name: Deploying DEV Infrastructure
        run: cdk deploy --require-approval never prod-aws-cdk-api-lambda-flask
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'